version: "3.8"
services:
  nacos:
    image: nacos/nacos-server:v2.2.2
    container_name: nacos-standalone-mysql8
    env_file:
      - ./nacos-standlone-mysql.env
    volumes:
      - ./standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
#    depends_on:
#      mysql:
#        condition: service_healthy
    restart: always
